
package controllers;

public enum ActionOfOperation {
    SHOW_SALARYS,SHOW_SALES_AND_EARNINGS,REWARDING_BEST_SELLER,FIRE_BAD_SELLER,COUPON_TO_THE_BEST_COUSTOMERS,DELETE_BAD_CUSTOMERS,RANDOM_DRAWING_OF_CUSTOMERS;
}
